parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json

plugins:
  - prettier
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

settings:
  react:
    version: detect

env:
  es6: true
  browser: true
rules:
  prettier/prettier: error
  '@typescript-eslint/indent': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: _
      argsIgnorePattern: _
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-inferrable-types': off
